baseURL = "https://main.dsil1b5ijwqvu.amplifyapp.com/"
# also at: http://datadog-test-site.s3-website-us-east-1.amazonaws.com/
languageCode = "en-us"
title = "Datadog Test Site"
theme = "datadog"

[menu]
  [[menu.main]]
    name = "Product"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Docs"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Pricing"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Customers"
    url = "/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 5
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 6

  [[menu.extra]]
    name = "Login"
    url = "/"