baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "datadog"
#theme = "bootstrap"

[menu]
  [[menu.main]]
    name = "Product"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Docs"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Pricing"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Customers"
    pre = "home"
    url = "/"
    weight = 4
  [[menu.main]]
    name = "About"
    pre = "home"
    url = "/"
    weight = 5
  [[menu.main]]
    name = "Blog"
    pre = "home"
    url = "/"
    weight = 6